name: Notion Issue Sync
description: Invokes a provided Make web-hook for syncing the state of an issue linked to the active PR
inputs:
  webhook:
    description: Make webhook for syncing issue state with Notion
    required: true
  token:
    description: Read-scoped GitHub token
    required: true
  event:
    description: Should be toJson(github.event) for extracting PR/review state
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
